## 다음과 같은 코드에서 나올 결과를 적고, 이렇게 나오는 이유를 설명하시오.

```py

from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical

text= "엔드 게임에서 아이언맨은 죽는다."

token = Tokenizer()
token.fit_on_texts([text])
x = token.texts_to_sequences([text])

word_size = len(token.word_index)+1
x = to_categorical(x, num_classes=word_size)

print(x)

```


In [36]:
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical

text= "엔드 게임에서 아이언맨은 죽는다."

token = Tokenizer()
token.fit_on_texts([text])
x = token.texts_to_sequences([text])

word_size = len(token.word_index)+1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]


단어의 one-hot encoding 을 했음 . 단어의 인덱스를 리스트의 인덱스와 맞추기 위해
앞에 0 을 추가로 삽입



## 문제 2
- 문장 세트1: "따끈한 라면 을 먹고 싶어.","맛 있는 밥 이 먹고 싶다"

- 문장 세트2: "맛 있게 밥솥 으로 밥 을 짓겠다.","맛 있는 밥 이 먹고 싶다"

두 문장의 유사도를 자카드 유사도로도, 코사인 유사도로도 구하시오.

In [37]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import jaccard_score
import numpy as np

sentences_set1 = ["따끈한 라면 을 먹고 싶어.", "맛 있는 밥 이 먹고 싶다"]
sentences_set2 = ["맛 있게 밥솥 으로 밥 을 짓겠다.", "맛 있는 밥 이 먹고 싶다"]

In [38]:
# CountVectorizer를 사용하여 단어 빈도수 벡터를 생성
vectorizer = CountVectorizer()
X_set1 = vectorizer.fit_transform(sentences_set1)
X_set2 = vectorizer.fit_transform(sentences_set2)
print(X_set1)

  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 4)	1
  (1, 2)	1
  (1, 5)	1
  (1, 3)	1


In [39]:
print(X_set2)

  (0, 4)	1
  (0, 1)	1
  (0, 3)	1
  (0, 6)	1
  (1, 5)	1
  (1, 0)	1
  (1, 2)	1


In [40]:
# 코사인 유사도 계산
cosine_sim_set1 = cosine_similarity(X_set1[0:1], X_set1[1:2])
cosine_sim_set2 = cosine_similarity(X_set2[0:1], X_set2[1:2])
cosine_sim_set1,cosine_sim_set2

(array([[0.28867513]]), array([[0.]]))

In [41]:
# TF-IDF Vectorizer를 사용하여 TF-IDF 벡터를 생성
tfidf_vectorizer = TfidfVectorizer()
X_set1_tfidf = tfidf_vectorizer.fit_transform(sentences_set1)
X_set2_tfidf = tfidf_vectorizer.fit_transform(sentences_set2)

print(X_set1_tfidf)
print()
print(X_set2_tfidf)
# 코사인 유사도 계산
cosine_sim_set1_tfidf = cosine_similarity(X_set1_tfidf[0:1], X_set1_tfidf[1:2])
cosine_sim_set2_tfidf = cosine_similarity(X_set2_tfidf[0:1], X_set2_tfidf[1:2])

cosine_sim_set1_tfidf,cosine_sim_set2_tfidf

  (0, 4)	0.534046329052269
  (0, 2)	0.37997836159100784
  (0, 1)	0.534046329052269
  (0, 0)	0.534046329052269
  (1, 3)	0.6316672017376245
  (1, 5)	0.6316672017376245
  (1, 2)	0.4494364165239821

  (0, 6)	0.5
  (0, 3)	0.5
  (0, 1)	0.5
  (0, 4)	0.5
  (1, 2)	0.5773502691896257
  (1, 0)	0.5773502691896257
  (1, 5)	0.5773502691896257


(array([[0.17077611]]), array([[0.]]))

In [42]:
binary_vec_set1 = X_set1.toarray().astype(np.bool_)
binary_vec_set2 = X_set2.toarray().astype(np.bool_)
binary_vec_set1,binary_vec_set2

(array([[ True,  True,  True, False,  True, False],
        [False, False,  True,  True, False,  True]]),
 array([[False,  True, False,  True,  True, False,  True],
        [ True, False,  True, False, False,  True, False]]))

In [43]:
# 자카드 유사도 계산
jaccard_sim_set1 = jaccard_score(binary_vec_set1[0], binary_vec_set1[1], average='binary')
jaccard_sim_set2 = jaccard_score(binary_vec_set2[0], binary_vec_set2[1], average='binary')
jaccard_sim_set1,jaccard_sim_set2

(0.16666666666666666, 0.0)